/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paper.GUI;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import paper.model.Mitra;
import paper.transaction.OrderPenjualan;

/**
 *
 * @author Deva
 */
public class InvoicePenjualanGUI extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePenjualanGUI
     */
    private ArrayList<OrderPenjualan> daftarOrder = new ArrayList<>();
    private ArrayList<Mitra> daftarMitra = new ArrayList<>();

    // Tambahkan di atas konstruktor
    private javax.swing.table.DefaultTableModel tableModel;
    private int selectedRow = -1;

    public InvoicePenjualanGUI() {
        initComponents();

        // Ambil data statis dari model
        daftarOrder.clear();

        // Isi cborderan hanya dengan nama mitra pelanggan dari order
        cborderan.removeAllItems();
        for (OrderPenjualan o : daftarOrder) {
            cborderan.addItem(o.getPelanggan().getNamaMitra());
        }

        // Set model tabel
        tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cborderan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtanggal = new javax.swing.JButton();
        jsubmit = new javax.swing.JButton();
        jedit = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INVOICE PENJUALAN");

        jLabel2.setText("Orderan");

        jLabel3.setText("Jatuh Tempo");

        cborderan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "orderan" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orderan", "Jatuh Tempo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jtanggal.setText("tanggal");

        jsubmit.setText("submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });

        jedit.setText("edit");
        jedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditActionPerformed(evt);
            }
        });

        jdelete.setText("delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        jtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsubmit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cborderan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtanggal, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cborderan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtanggal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsubmit)
                    .addComponent(jedit)
                    .addComponent(jdelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        int idxOrder = cborderan.getSelectedIndex();
        if (idxOrder < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih orderan!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String namaOrder = (String) cborderan.getSelectedItem();
        String tanggal = jtanggal.getText();

        // Tambahkan ke tabel
        tableModel.addRow(new Object[]{namaOrder, tanggal});
        jTable1.clearSelection();
        selectedRow = -1;
    }//GEN-LAST:event_jsubmitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String namaOrder = (String) tableModel.getValueAt(selectedRow, 0);
            String tanggal = (String) tableModel.getValueAt(selectedRow, 1);

            cborderan.setSelectedItem(namaOrder);
            jtanggal.setText(tanggal);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditActionPerformed
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Klik baris tabel yang ingin diedit!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int idxOrder = cborderan.getSelectedIndex();
        if (idxOrder < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih orderan!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String namaOrder = (String) cborderan.getSelectedItem();
        String tanggal = jtanggal.getText();

        tableModel.setValueAt(namaOrder, selectedRow, 0);
        tableModel.setValueAt(tanggal, selectedRow, 1);
        jTable1.clearSelection();
        selectedRow = -1;
    }//GEN-LAST:event_jeditActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Klik baris tabel yang ingin dihapus!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            tableModel.removeRow(selectedRow);
            jTable1.clearSelection();
            selectedRow = -1;
        }
    }//GEN-LAST:event_jdeleteActionPerformed

    private Date tanggalDipilih = new Date(); // default hari ini

    private void jtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtanggalActionPerformed
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String input = javax.swing.JOptionPane.showInputDialog(
            this,
            "Masukkan tanggal dengan format yyyy-MM-dd:",
            sdf.format(tanggalDipilih)
        );
        if (input != null && !input.isEmpty()) {
            try {
                tanggalDipilih = sdf.parse(input);
                jtanggal.setText(input);
            } catch (ParseException ex) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Format tanggal salah! Contoh: 2025-06-08",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_jtanggalActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cborderan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jedit;
    private javax.swing.JButton jsubmit;
    private javax.swing.JButton jtanggal;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Invoice Penjualan");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new InvoicePenjualanGUI());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
