/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paper.GUI;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import paper.model.Produk;
import paper.model.Mitra;

/**
 *
 * @author Deva
 */
public class NewJFrame extends javax.swing.JFrame {

    private JPanel contentPanel;
    private JPanel homePanel;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setTitle("Dashboard");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        contentPanel = new JPanel(new BorderLayout());
        homePanel = new JPanel();
        homePanel.setLayout(new GridBagLayout());
        JLabel lblWelcome = new JLabel("Selamat Datang di Dashboard");
        lblWelcome.setFont(new Font("Segoe UI", Font.BOLD, 20));
        homePanel.add(lblWelcome);

        add(contentPanel, BorderLayout.CENTER);

        jlogout.setVisible(false);
        showPanel(new LoginGUI(this));
    }

    // Method untuk menampilkan panel di contentPanel
    void showPanel(Component panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jproduk = new javax.swing.JMenuItem();
        jstok = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmitra = new javax.swing.JMenuItem();
        jnetwork = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jlaporangui = new javax.swing.JMenuItem();
        jpembelian = new javax.swing.JMenuItem();
        jpenjualan = new javax.swing.JMenuItem();
        jbtn = new javax.swing.JMenu();
        jlogin = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Produk");

        jproduk.setText("ProdukGUI");
        jproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprodukActionPerformed(evt);
            }
        });
        jMenu1.add(jproduk);

        jstok.setText("Stok");
        jstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstokActionPerformed(evt);
            }
        });
        jMenu1.add(jstok);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mitra");

        jmitra.setText("MitraGUI");
        jmitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitraActionPerformed(evt);
            }
        });
        jMenu2.add(jmitra);

        jnetwork.setText("Network");
        jnetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnetworkActionPerformed(evt);
            }
        });
        jMenu2.add(jnetwork);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        jlaporangui.setText("LaporanGUI");
        jlaporangui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanguiActionPerformed(evt);
            }
        });
        jMenu3.add(jlaporangui);

        jpembelian.setText("Pembelian");
        jpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpembelianActionPerformed(evt);
            }
        });
        jMenu3.add(jpembelian);

        jpenjualan.setText("Penjualan");
        jpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(jpenjualan);

        jMenuBar1.add(jMenu3);

        jbtn.setText("User");

        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        jbtn.add(jlogin);

        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jbtn.add(jlogout);

        jMenuBar1.add(jbtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Contoh pemanggilan pada menu event:
    private void jprodukActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel(new ProdukGUI());
    }

    private void jstokActionPerformed(java.awt.event.ActionEvent evt) {                                      
        showPanel(new StokGUI());
    }

    private void jmitraActionPerformed(java.awt.event.ActionEvent evt) {                                       
        showPanel(new MitraForm());
    }

    private void jnetworkActionPerformed(java.awt.event.ActionEvent evt) {                                         
        showPanel(new PaperNetworkGUI());
    }

    private void jpembelianActionPerformed(java.awt.event.ActionEvent evt) {                                           
        showPanel(new OrderPembelian());
    }

    private void jpenjualanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        showPanel(new OrderPenjualanGUI());
    }

    private boolean isLoggedIn = false;
    private String username = "User";

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isLoggedIn) {
            // Tampilkan panel login
            showPanel(new LoginGUI(this)); // Pastikan LoginGUI bisa menerima NewJFrame sebagai parameter
        } else {
            // Sudah login, tampilkan dashboard
            showPanel(new Dashboard(username));
        }
    }

    // Method ini dipanggil dari LoginGUI setelah login sukses
    public void onLoginSuccess(String username) {
        this.isLoggedIn = true;
        this.username = username;
        jlogin.setText("Dashboard");
        jlogout.setVisible(true); // Tampilkan tombol logout setelah login
        showPanel(new Dashboard(username));
    }

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {
        isLoggedIn = false;
        username = "User";
        jlogin.setText("Login");
        jlogout.setVisible(false);
        showPanel(new LoginGUI(this)); // langsung ke LoginGUI
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new NewJFrame().setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jbtn;
    private javax.swing.JMenuItem jlaporangui;
    private javax.swing.JMenuItem jlogin;
    private javax.swing.JMenuItem jlogout;
    private javax.swing.JMenuItem jmitra;
    private javax.swing.JMenuItem jnetwork;
    private javax.swing.JMenuItem jpembelian;
    private javax.swing.JMenuItem jpenjualan;
    private javax.swing.JMenuItem jproduk;
    private javax.swing.JMenuItem jstok;
    // End of variables declaration//GEN-END:variables
}
