/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paper.GUI;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Deva
 */
public class NewJFrame extends javax.swing.JFrame {

    private JPanel sidebar;
    private JPanel contentPanel;
    private JButton btnProduk, btnStok, btnMitra, btnNetwork, btnLaporan, btnPembelian, btnPenjualan, btnBack;
    private JPanel homePanel;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setTitle("Dashboard");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Sidebar
        sidebar = new JPanel();
        sidebar.setLayout(new GridLayout(0, 1, 0, 10));
        sidebar.setBackground(new Color(40, 40, 60));
        sidebar.setPreferredSize(new Dimension(150, 0));

        btnProduk = new JButton("Produk");
        btnStok = new JButton("Stok");
        btnMitra = new JButton("Mitra");
        btnNetwork = new JButton("Network");
        btnLaporan = new JButton("Laporan");
        btnPembelian = new JButton("Pembelian");
        btnPenjualan = new JButton("Penjualan");
        btnBack = new JButton("Back");

        sidebar.add(btnProduk);
        sidebar.add(btnStok);
        sidebar.add(btnMitra);
        sidebar.add(btnNetwork);
        sidebar.add(btnLaporan);
        sidebar.add(btnPembelian);
        sidebar.add(btnPenjualan);
        sidebar.add(Box.createVerticalGlue());
        sidebar.add(btnBack);

        // Content Panel
        contentPanel = new JPanel(new BorderLayout());

        // Home Panel (dashboard utama)
        homePanel = new JPanel();
        homePanel.setLayout(new GridBagLayout());
        JLabel lblWelcome = new JLabel("Selamat Datang di Dashboard");
        lblWelcome.setFont(new Font("Segoe UI", Font.BOLD, 20));
        homePanel.add(lblWelcome);

        contentPanel.add(homePanel, BorderLayout.CENTER);

        // Add to frame
        add(sidebar, BorderLayout.WEST);
        add(contentPanel, BorderLayout.CENTER);

        // Action Listeners
        btnProduk.addActionListener(e -> showPanel(new ProdukGUI()));
        btnStok.addActionListener(e -> showPanel(new StokGUI()));
        btnMitra.addActionListener(e -> showPanel(new MitraGUI()));
        btnNetwork.addActionListener(e -> showPanel(new NetworkGUI()));
        btnLaporan.addActionListener(e -> showPanel(new LaporanGUI()));
        btnPembelian.addActionListener(e -> showPanel(new InvoicePembelianGUI().getContentPane()));
        btnPenjualan.addActionListener(e -> showPanel(new PenjualanGUI()));
        btnBack.addActionListener(e -> showPanel(homePanel));
    }

    // Method untuk menampilkan panel di contentPanel
    private void showPanel(Component panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jproduk = new javax.swing.JMenuItem();
        jstok = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmitra = new javax.swing.JMenuItem();
        jnetwork = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jlaporangui = new javax.swing.JMenuItem();
        jpembelian = new javax.swing.JMenuItem();
        jpenjualan = new javax.swing.JMenuItem();
        jbtn = new javax.swing.JMenu();
        jlogin = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jMenu1.setText("Produk");

        jproduk.setText("ProdukGUI");
        jproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprodukActionPerformed(evt);
            }
        });
        jMenu1.add(jproduk);

        jstok.setText("Stok");
        jstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstokActionPerformed(evt);
            }
        });
        jMenu1.add(jstok);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mitra");

        jmitra.setText("MitraGUI");
        jmitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitraActionPerformed(evt);
            }
        });
        jMenu2.add(jmitra);

        jnetwork.setText("Network");
        jnetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnetworkActionPerformed(evt);
            }
        });
        jMenu2.add(jnetwork);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        jlaporangui.setText("LaporanGUI");
        jlaporangui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanguiActionPerformed(evt);
            }
        });
        jMenu3.add(jlaporangui);

        jpembelian.setText("Pembelian");
        jpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpembelianActionPerformed(evt);
            }
        });
        jMenu3.add(jpembelian);

        jpenjualan.setText("Penjualan");
        jpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(jpenjualan);

        jMenuBar1.add(jMenu3);

        jbtn.setText("User");

        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        jbtn.add(jlogin);

        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jbtn.add(jlogout);

        jMenuBar1.add(jbtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstokActionPerformed

    private void jprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprodukActionPerformed

    private void jmitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitraActionPerformed

    private void jnetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnetworkActionPerformed

    private void jlaporanguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanguiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlaporanguiActionPerformed

    private void jpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpembelianActionPerformed

    private void jpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpenjualanActionPerformed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new NewJFrame().setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jbtn;
    private javax.swing.JMenuItem jlaporangui;
    private javax.swing.JMenuItem jlogin;
    private javax.swing.JMenuItem jlogout;
    private javax.swing.JMenuItem jmitra;
    private javax.swing.JMenuItem jnetwork;
    private javax.swing.JMenuItem jpembelian;
    private javax.swing.JMenuItem jpenjualan;
    private javax.swing.JMenuItem jproduk;
    private javax.swing.JMenuItem jstok;
    // End of variables declaration//GEN-END:variables
}
