/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paper.GUI;

import paper.model.Mitra;
import java.util.ArrayList;
import paper.model.Produk;

/**
 *
 * @author Deva
 */
public class OrderPenjualanGUI extends javax.swing.JPanel {
    private ArrayList<Produk> daftarProduk = new ArrayList<>();
    private ArrayList<Mitra> daftarMitra = new ArrayList<>();

    // Tambahkan di atas konstruktor
    private javax.swing.table.DefaultTableModel tableModel;
    private java.util.List<Object> detailTransaksi = new java.util.ArrayList<>();

    public OrderPenjualanGUI() {
        initComponents();

        // Contoh data produk
        if (daftarProduk.isEmpty()) {
            daftarProduk.add(new Produk("P001", "Kertas A4", 25000, 20000, "Kertas ukuran A4 80gsm"));
            daftarProduk.add(new Produk("P002", "Pulpen", 5000, 3000, "Pulpen tinta biru"));
            daftarProduk.add(new Produk("P003", "Buku Tulis", 12000, 9000, "Buku tulis 40 lembar"));
        }

        // Contoh data mitra
        if (daftarMitra.isEmpty()) {
            daftarMitra.add(new Mitra("M001", "Toko Sukses", "Toko", "Jl. Merdeka No.1", "08123456789", "sukses@toko.com", "Budi"));
            daftarMitra.add(new Mitra("M002", "Mitra Jaya", "Distributor", "Jl. Jaya No.2", "08234567890", "jaya@mitra.com", "Siti"));
            daftarMitra.add(new Mitra("M003", "CV Lancar", "CV", "Jl. Lancar No.3", "08345678901", "lancar@cv.com", "Andi"));
        }

        // Isi dropproduk hanya dengan nama produk
        dropproduk.removeAllItems();
        for (Produk p : daftarProduk) {
            dropproduk.addItem(p.getNama());
        }

        // Isi dopmitra hanya dengan nama mitra
        dopmitra.removeAllItems();
        for (Mitra m : daftarMitra) {
            dopmitra.addItem(m.getNamaMitra());
        }

        // Set model tabel
        tableModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"Produk", "Mitra"}, 0
        );
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropproduk = new javax.swing.JComboBox<>();
        dopmitra = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jsubmit = new javax.swing.JButton();
        jedit = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();

        dropproduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "produk" }));

        dopmitra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mitra" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ORDER PENJUALAN");

        jLabel2.setText("Daftar Produk");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Daftar Produk", "Mitra"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Mitra");

        jsubmit.setText("submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });

        jedit.setText("edit");
        jedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditActionPerformed(evt);
            }
        });

        jdelete.setText("delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropproduk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dopmitra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dopmitra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsubmit)
                    .addComponent(jedit)
                    .addComponent(jdelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        int idxProduk = dropproduk.getSelectedIndex();
        int idxMitra = dopmitra.getSelectedIndex();
        if (idxProduk < 0 || idxMitra < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih produk dan mitra!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String namaProduk = daftarProduk.get(idxProduk).getNama();
        String namaMitra = daftarMitra.get(idxMitra).getNamaMitra();

        // Tambahkan ke tabel
        tableModel.addRow(new Object[]{namaProduk, namaMitra});
        jTable1.clearSelection();
    }//GEN-LAST:event_jsubmitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Ambil nama produk dan mitra dari tabel
            String namaProduk = (String) tableModel.getValueAt(selectedRow, 0);
            String namaMitra = (String) tableModel.getValueAt(selectedRow, 1);

            // Pilih item di combo box sesuai nama
            dropproduk.setSelectedItem(namaProduk);
            dopmitra.setSelectedItem(namaMitra);
        }
    }//GEN-LAST:event_jTable1MouseClicked


    private void jeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit di tabel!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int idxProduk = dropproduk.getSelectedIndex();
        int idxMitra = dopmitra.getSelectedIndex();
        if (idxProduk < 0 || idxMitra < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih produk dan mitra!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String namaProduk = daftarProduk.get(idxProduk).getNama();
        String namaMitra = daftarMitra.get(idxMitra).getNamaMitra();

        // Update data di tabel
        tableModel.setValueAt(namaProduk, selectedRow, 0);
        tableModel.setValueAt(namaMitra, selectedRow, 1);
        jTable1.clearSelection();
    }//GEN-LAST:event_jeditActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus di tabel!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            tableModel.removeRow(selectedRow);
            jTable1.clearSelection();
        }
    }//GEN-LAST:event_jdeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dopmitra;
    private javax.swing.JComboBox<String> dropproduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jedit;
    private javax.swing.JButton jsubmit;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Order Penjualan");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new OrderPenjualanGUI());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
