/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paper.GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import paper.model.PaperNetwork;

/**
 *
 * @author Deva
 */
public class PaperNetworkGUI extends javax.swing.JPanel {
    public static List<PaperNetwork> dataNet = new ArrayList<>();
    /**
     * Creates new form PaperNetwork
     */
    public PaperNetworkGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idp = new javax.swing.JTextField();
        jenisp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbValid = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jEdit = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jsbumit = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PAPER NETWORK");
        jLabel1.setName("paper"); // NOI18N

        idp.setEditable(false);
        idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpActionPerformed(evt);
            }
        });

        jenisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenispActionPerformed(evt);
            }
        });

        jLabel2.setText("ID PAPER NETWORK");

        jLabel3.setText("JENIS PAPER NETWORK");

        jLabel4.setText("SATUS PAPER NETWORK");

        cbValid.setText("valid");
        cbValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValidActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jenis", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jEdit.setText("edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jDelete.setText("delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jsbumit.setText("submit");
        jsbumit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsbumitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbValid, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsbumit)))
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbValid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEdit)
                    .addComponent(jDelete)
                    .addComponent(jsbumit))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpActionPerformed

    private void cbValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbValidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    // 1. Dapatkan nomor baris yang di-klik
    int selectedRow = jTable1.getSelectedRow();
    
    // Pastikan ada baris yang benar-benar dipilih (bukan header atau area kosong)
    if (selectedRow == -1) {
        return; 
    }
    
    // 2. Ambil data dari setiap kolom di baris yang dipilih
    String id = jTable1.getModel().getValueAt(selectedRow, 0).toString();
    String jenis = jTable1.getModel().getValueAt(selectedRow, 1).toString();
    String status = jTable1.getModel().getValueAt(selectedRow, 2).toString();
    
    // 3. Masukkan data tersebut ke dalam komponen form Anda
    idp.setText(id);
    jenisp.setText(jenis);
    
    // Atur checkbox berdasarkan nilai status dari tabel
    if (status.equals("Valid")) {
        cbValid.setSelected(true);
    } else {
        cbValid.setSelected(false);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jenispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenispActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diupdate.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Ambil data baru dari form
    String jenisBaru = jenisp.getText();
    boolean statusBaru = cbValid.isSelected();
    String statusTabel = statusBaru ? "Valid" : "Tidak Valid";

    // Update data di tabel (tampilan)
    jTable1.setValueAt(jenisBaru, selectedRow, 1);
    jTable1.setValueAt(statusTabel, selectedRow, 2);
    
    String idLama = dataNet.get(selectedRow).getIdPaper();
    PaperNetwork paperBaru = new PaperNetwork(idLama, jenisBaru, statusBaru);

    dataNet.set(selectedRow, paperBaru);
    JOptionPane.showMessageDialog(this, "Data berhasil diupdate.");
    }//GEN-LAST:event_jEditActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
    // 1. Dapatkan baris mana yang sedang dipilih di tabel
    int selectedRow = jTable1.getSelectedRow();
    
    // 2. Periksa apakah ada baris yang dipilih. Jika tidak, tampilkan error.
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Hentikan eksekusi jika tidak ada baris terpilih
    }
    
    // 3. Tampilkan dialog konfirmasi untuk keamanan
    int confirm = JOptionPane.showConfirmDialog(this, 
                                                "Apakah Anda yakin ingin menghapus data ini?", 
                                                "Konfirmasi Hapus", 
                                                JOptionPane.YES_NO_OPTION);
    
    // 4. Jika pengguna menekan tombol "Yes" (konfirmasi)
    if (confirm == JOptionPane.YES_OPTION) {
        // A. Hapus data dari sumber utamanya (ArrayList)
        // Pastikan kita menggunakan 'dataNet' sesuai kesepakatan terakhir
        dataNet.remove(selectedRow);
        
        // B. Hapus baris dari tampilannya (JTable)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.removeRow(selectedRow);
        
        // C. Tampilkan pesan sukses
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
        
        // D. Kosongkan kembali form input
        idp.setText("");
        jenisp.setText("");
        cbValid.setSelected(false);
    }
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jsbumitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsbumitActionPerformed
        // 1. Ambil data dari komponen form menggunakan nama variabel yang benar
        String idPaper = String.valueOf((int)(Math.random() * 1000000));
        String jenisPaper = jenisp.getText();
        boolean isValid = cbValid.isSelected();

        // 2. Lakukan validasi input
        if (idPaper.isEmpty() || jenisPaper.isEmpty()) {
            // Tampilkan pesan error jika ada yang kosong
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Jenis Paper Network wajib diisi!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Jika semua terisi, lanjutkan proses

            // 3. Buat objek baru dari kelas PaperNetwork
            PaperNetwork paperBaru = new PaperNetwork(idPaper, jenisPaper, isValid);

            // 4. Tambahkan objek baru ke ArrayList (dataNet)
            dataNet.add(paperBaru);

            // 5. Tambahkan baris baru ke JTable (jTable1)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            String statusUntukTabel = isValid ? "Valid" : "Tidak Valid";
            model.addRow(new Object[]{idPaper, jenisPaper, statusUntukTabel});

            // 6. Kosongkan kembali form input untuk data selanjutnya
            idp.setText("");
            jenisp.setText("");
            cbValid.setSelected(false);

            // 7. Tampilkan pesan sukses (opsional)
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jsbumitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbValid;
    private javax.swing.JTextField idp;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jenisp;
    private javax.swing.JButton jsbumit;
    // End of variables declaration//GEN-END:variables
    
        public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Aplikasi Paper Network");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new PaperNetworkGUI());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
